-- MySQL Script generated by MySQL Workbench
-- 09/06/15 20:42:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sigi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sigi
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `sigi` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sigi` ;

-- -----------------------------------------------------
-- Table `sigi`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`permisos` (
  `id_permiso` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_permiso`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `fecha_inicio_actividad` DATE NULL COMMENT '',
  `cuit` VARCHAR(45) NULL COMMENT '',
  `tipo_fiscal` VARCHAR(45) NULL COMMENT '',
  `direccion` VARCHAR(45) NULL COMMENT '',
  `telefono` INT NULL COMMENT '',
  `fax` INT NULL COMMENT '',
  `facturacion_anual` INT NULL COMMENT '',
  `logo` INT NULL COMMENT '',
  `responsable` VARCHAR(45) NULL COMMENT '',
  `id_usuario` INT NULL COMMENT '',
  PRIMARY KEY (`id_empresa`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`forma_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`forma_pago` (
  `id_forma_pago` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_forma_pago`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`iva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`iva` (
  `id_iva` INT NOT NULL COMMENT '',
  `valor` INT NULL COMMENT '',
  PRIMARY KEY (`id_iva`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`ventas` (
  `id_venta` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha` DATE NULL COMMENT '',
  `id_usuario` INT NULL COMMENT '',
  `total` INT NULL COMMENT '',
  `descuento` INT NULL COMMENT '',
  `forma_pago_id_forma_pago` INT NOT NULL COMMENT '',
  `iva_id_iva` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_venta`)  COMMENT '',
  INDEX `fk_ventas_forma_pago1_idx` (`forma_pago_id_forma_pago` ASC)  COMMENT '',
  INDEX `fk_ventas_iva1_idx` (`iva_id_iva` ASC)  COMMENT '',
  CONSTRAINT `fk_ventas_forma_pago1`
    FOREIGN KEY (`forma_pago_id_forma_pago`)
    REFERENCES `sigi`.`forma_pago` (`id_forma_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_iva1`
    FOREIGN KEY (`iva_id_iva`)
    REFERENCES `sigi`.`iva` (`id_iva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(50) NULL COMMENT '',
  `apellido_paterno` VARCHAR(50) NULL COMMENT '',
  `apellido_materno` VARCHAR(50) NULL COMMENT '',
  `user` VARCHAR(50) NULL COMMENT '',
  `pass` VARCHAR(128) NULL COMMENT '',
  `nivel` VARCHAR(50) NULL COMMENT '',
  `fecha_ing` DATETIME NULL COMMENT '',
  `fecha_nac` DATE NULL COMMENT '',
  `direccion` VARCHAR(255) NULL COMMENT '',
  `telefono` INT NULL COMMENT '',
  `cel` INT NULL COMMENT '',
  `mail` VARCHAR(50) NULL COMMENT '',
  `permisos_id_permiso` INT NOT NULL COMMENT '',
  `empresa_id_empresa` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_usuario`)  COMMENT '',
  INDEX `fk_usuarios_permisos_idx` (`permisos_id_permiso` ASC)  COMMENT '',
  INDEX `fk_usuarios_empresa1_idx` (`empresa_id_empresa` ASC)  COMMENT '',
  CONSTRAINT `fk_usuarios_permisos`
    FOREIGN KEY (`permisos_id_permiso`)
    REFERENCES `sigi`.`permisos` (`id_permiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_empresa1`
    FOREIGN KEY (`empresa_id_empresa`)
    REFERENCES `sigi`.`empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`clientes` (
  `id_clientes` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellido` VARCHAR(45) NULL COMMENT '',
  `direccion` VARCHAR(255) NULL COMMENT '',
  `mail` VARCHAR(45) NULL COMMENT '',
  `telefono` INT NULL COMMENT '',
  `celular` INT NULL COMMENT '',
  `fecha_alta` DATE NULL COMMENT '',
  PRIMARY KEY (`id_clientes`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`proveedores` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellido` VARCHAR(45) NULL COMMENT '',
  `direccion` VARCHAR(45) NULL COMMENT '',
  `mail` VARCHAR(45) NULL COMMENT '',
  `telefono` VARCHAR(45) NULL COMMENT '',
  `cel` VARCHAR(45) NULL COMMENT '',
  `nombre_empresa` VARCHAR(45) NULL COMMENT '',
  `id_sector` INT NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_proveedor`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`subfamilia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`subfamilia` (
  `id_subfamilia` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `id_familia` INT NULL COMMENT '',
  PRIMARY KEY (`id_subfamilia`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`familia` (
  `id_familia` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `subfamilia_id_subfamilia` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_familia`)  COMMENT '',
  INDEX `fk_familia_subfamilia1_idx` (`subfamilia_id_subfamilia` ASC)  COMMENT '',
  CONSTRAINT `fk_familia_subfamilia1`
    FOREIGN KEY (`subfamilia_id_subfamilia`)
    REFERENCES `sigi`.`subfamilia` (`id_subfamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`sector` (
  `id_sector` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_sector`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`stock` (
  `id_stock` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_articulo` INT NULL COMMENT '',
  `saldo_stock` INT NULL COMMENT '',
  `incremento` INT NULL COMMENT '',
  `fecha_salida` DATE NULL COMMENT '',
  `salida` INT NULL COMMENT '',
  `fecha_entrada` DATE NULL COMMENT '',
  `entrada` INT NULL COMMENT '',
  `id_producto_propio` INT NULL COMMENT '',
  PRIMARY KEY (`id_stock`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`articulos` (
  `id_articulo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `scanning` VARCHAR(255) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `fecha_alta` DATE NULL COMMENT '',
  `fecha_baja` DATE NULL COMMENT '',
  `unidad` INT NULL COMMENT '',
  `proveedores_id_proveedor` INT NOT NULL COMMENT '',
  `familia_id_familia` INT NOT NULL COMMENT '',
  `sector_id_sector` INT NOT NULL COMMENT '',
  `stock_id_stock` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_articulo`)  COMMENT '',
  INDEX `fk_articulos_proveedores1_idx` (`proveedores_id_proveedor` ASC)  COMMENT '',
  INDEX `fk_articulos_familia1_idx` (`familia_id_familia` ASC)  COMMENT '',
  INDEX `fk_articulos_sector1_idx` (`sector_id_sector` ASC)  COMMENT '',
  INDEX `fk_articulos_stock1_idx` (`stock_id_stock` ASC)  COMMENT '',
  CONSTRAINT `fk_articulos_proveedores1`
    FOREIGN KEY (`proveedores_id_proveedor`)
    REFERENCES `sigi`.`proveedores` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulos_familia1`
    FOREIGN KEY (`familia_id_familia`)
    REFERENCES `sigi`.`familia` (`id_familia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulos_sector1`
    FOREIGN KEY (`sector_id_sector`)
    REFERENCES `sigi`.`sector` (`id_sector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulos_stock1`
    FOREIGN KEY (`stock_id_stock`)
    REFERENCES `sigi`.`stock` (`id_stock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`detalle_venta` (
  `id_detalle_venta` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `scanning` VARCHAR(255) NULL COMMENT '',
  `cantidad` INT NULL COMMENT '',
  `ventas_id_venta` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_detalle_venta`)  COMMENT '',
  INDEX `fk_detalle_venta_ventas1_idx` (`ventas_id_venta` ASC)  COMMENT '',
  CONSTRAINT `fk_detalle_venta_ventas1`
    FOREIGN KEY (`ventas_id_venta`)
    REFERENCES `sigi`.`ventas` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`ordenes_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`ordenes_compra` (
  `id_ordenes_compra` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha_alta` DATE NULL COMMENT '',
  `id_usuario` INT NULL COMMENT '',
  `id_proveedor` INT NULL COMMENT '',
  `total` INT NULL COMMENT '',
  `fecha_aprobado` DATE NULL COMMENT '',
  `fecha_estimada_recepcion` DATE NULL COMMENT '',
  `id_forma_pago` INT NULL COMMENT '',
  PRIMARY KEY (`id_ordenes_compra`)  COMMENT '',
  INDEX `id_forma_pago_idx` (`id_forma_pago` ASC)  COMMENT '',
  CONSTRAINT `id_forma_pago`
    FOREIGN KEY (`id_forma_pago`)
    REFERENCES `sigi`.`forma_pago` (`id_forma_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`compras` (
  `id_compras` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha` DATE NULL COMMENT '',
  `total` INT NULL COMMENT '',
  `id_pago` INT NULL COMMENT '',
  `id_usuario` INT NULL COMMENT '',
  `numero_factura` INT NULL COMMENT '',
  `archivo` VARCHAR(255) NULL COMMENT '',
  `cc` VARCHAR(255) NULL COMMENT '',
  `proveedores_id_proveedor` INT NOT NULL COMMENT '',
  `ordenes_compra_id_ordenes_compra` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_compras`)  COMMENT '',
  INDEX `fk_compras_proveedores1_idx` (`proveedores_id_proveedor` ASC)  COMMENT '',
  INDEX `fk_compras_ordenes_compra1_idx` (`ordenes_compra_id_ordenes_compra` ASC)  COMMENT '',
  CONSTRAINT `fk_compras_proveedores1`
    FOREIGN KEY (`proveedores_id_proveedor`)
    REFERENCES `sigi`.`proveedores` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_ordenes_compra1`
    FOREIGN KEY (`ordenes_compra_id_ordenes_compra`)
    REFERENCES `sigi`.`ordenes_compra` (`id_ordenes_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`detalle_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`detalle_compra` (
  `id_detalle_compra` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `scanning` VARCHAR(255) NULL COMMENT '',
  `cantidad` INT NULL COMMENT '',
  `observacion` VARCHAR(180) NULL COMMENT '',
  `ubicacion` VARCHAR(45) NULL COMMENT '',
  `compras_id_compras` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_detalle_compra`)  COMMENT '',
  INDEX `fk_detalle_compra_compras1_idx` (`compras_id_compras` ASC)  COMMENT '',
  CONSTRAINT `fk_detalle_compra_compras1`
    FOREIGN KEY (`compras_id_compras`)
    REFERENCES `sigi`.`compras` (`id_compras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`auditoria` (
  `id_auditoria` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_modulo` INT NULL COMMENT '',
  `fecha_hs` DATE NULL COMMENT '',
  `accion` VARCHAR(45) NULL COMMENT '',
  `importes` INT NULL COMMENT '',
  `id_usuario` INT NULL COMMENT '',
  `id_cliente` INT NULL COMMENT '',
  `id_proveedor` INT NULL COMMENT '',
  `descripcion` VARCHAR(180) NULL COMMENT '',
  PRIMARY KEY (`id_auditoria`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`tesoreria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`tesoreria` (
  `id_tesoreria` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha_apertura` DATE NULL COMMENT '',
  `apertura_caja` INT NULL COMMENT '',
  `id_venta` INT NULL COMMENT '',
  `venta` INT NULL COMMENT '',
  `id_compra` INT NULL COMMENT '',
  `compra` INT NULL COMMENT '',
  `salida_caja` INT NULL COMMENT '',
  `descripcion_salida` VARCHAR(180) NULL COMMENT '',
  `emtrada_caja` INT NULL COMMENT '',
  `descripcion_entrada` VARCHAR(180) NULL COMMENT '',
  `cierre_caja` INT NULL COMMENT '',
  `fecha_cierre` DATE NULL COMMENT '',
  PRIMARY KEY (`id_tesoreria`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`marketing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`marketing` (
  `id_marketing` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `archivo` VARCHAR(45) NULL COMMENT '',
  `fecha` DATE NULL COMMENT '',
  `id_usuario` INT NULL COMMENT '',
  `scanning` VARCHAR(255) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_marketing`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`pre_oferta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`pre_oferta` (
  `id_pre_oferta` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `fecha_creacion` DATE NULL COMMENT '',
  `id_usuario` INT NULL COMMENT '',
  `fecha_inicio` DATE NULL COMMENT '',
  `fecha_fin` DATE NULL COMMENT '',
  `descripcion` VARCHAR(180) NULL COMMENT '',
  `porcentaje_descuento` INT NULL COMMENT '',
  `stock_disponible` INT NULL COMMENT '',
  `familia_id_familia` INT NOT NULL COMMENT '',
  `subfamilia_id_subfamilia` INT NOT NULL COMMENT '',
  `marketing_id_marketing` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_pre_oferta`)  COMMENT '',
  INDEX `fk_pre_oferta_familia1_idx` (`familia_id_familia` ASC)  COMMENT '',
  INDEX `fk_pre_oferta_subfamilia1_idx` (`subfamilia_id_subfamilia` ASC)  COMMENT '',
  INDEX `fk_pre_oferta_marketing1_idx` (`marketing_id_marketing` ASC)  COMMENT '',
  CONSTRAINT `fk_pre_oferta_familia1`
    FOREIGN KEY (`familia_id_familia`)
    REFERENCES `sigi`.`familia` (`id_familia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pre_oferta_subfamilia1`
    FOREIGN KEY (`subfamilia_id_subfamilia`)
    REFERENCES `sigi`.`subfamilia` (`id_subfamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pre_oferta_marketing1`
    FOREIGN KEY (`marketing_id_marketing`)
    REFERENCES `sigi`.`marketing` (`id_marketing`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`rrhh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`rrhh` (
  `id_rrhh` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_usuario` INT NULL COMMENT '',
  `fecha_inicio` DATE NULL COMMENT '',
  `fecha_fin` DATE NULL COMMENT '',
  `usuarios_id_usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_rrhh`)  COMMENT '',
  INDEX `fk_rrhh_usuarios1_idx` (`usuarios_id_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_rrhh_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `sigi`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`rrhh_sueldos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`rrhh_sueldos` (
  `id_rrhh_sueldos` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `sueldo_basico` INT NULL COMMENT '',
  `retencion` INT NULL COMMENT '',
  `sueldo_mano` INT NULL COMMENT '',
  `periodo` DATE NULL COMMENT '',
  `fecha_pago` DATE NULL COMMENT '',
  `jornada` DATE NULL COMMENT '',
  `rrhh_id_rrhh` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_rrhh_sueldos`)  COMMENT '',
  INDEX `fk_rrhh_sueldos_rrhh1_idx` (`rrhh_id_rrhh` ASC)  COMMENT '',
  CONSTRAINT `fk_rrhh_sueldos_rrhh1`
    FOREIGN KEY (`rrhh_id_rrhh`)
    REFERENCES `sigi`.`rrhh` (`id_rrhh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`cuenta_corriente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`cuenta_corriente` (
  `id_cuenta_corriente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha` DATE NULL COMMENT '',
  `total` INT NULL COMMENT '',
  `suma` INT NULL COMMENT '',
  `resta` INT NULL COMMENT '',
  `clientes_id_clientes` INT NOT NULL COMMENT '',
  `usuarios_id_usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_cuenta_corriente`)  COMMENT '',
  INDEX `fk_cuenta_corriente_clientes1_idx` (`clientes_id_clientes` ASC)  COMMENT '',
  INDEX `fk_cuenta_corriente_usuarios1_idx` (`usuarios_id_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_cuenta_corriente_clientes1`
    FOREIGN KEY (`clientes_id_clientes`)
    REFERENCES `sigi`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_corriente_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `sigi`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`mensajes` (
  `id_mensajes` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha` DATE NULL COMMENT '',
  `mensaje` VARCHAR(45) NULL COMMENT '',
  `id_usuario_creacion` INT NULL COMMENT '',
  `id_usuario_destino` INT NULL COMMENT '',
  PRIMARY KEY (`id_mensajes`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`producto_propio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`producto_propio` (
  `id_producto_propio` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `scanning` VARCHAR(255) NULL COMMENT '',
  `fecha_alta` DATE NULL COMMENT '',
  `descripcion` VARCHAR(180) NULL COMMENT '',
  `unidades` INT NULL COMMENT '',
  `proveedores_id_proveedor` INT NOT NULL COMMENT '',
  `stock_id_stock` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_producto_propio`)  COMMENT '',
  INDEX `fk_producto_propio_proveedores1_idx` (`proveedores_id_proveedor` ASC)  COMMENT '',
  INDEX `fk_producto_propio_stock1_idx` (`stock_id_stock` ASC)  COMMENT '',
  CONSTRAINT `fk_producto_propio_proveedores1`
    FOREIGN KEY (`proveedores_id_proveedor`)
    REFERENCES `sigi`.`proveedores` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_propio_stock1`
    FOREIGN KEY (`stock_id_stock`)
    REFERENCES `sigi`.`stock` (`id_stock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`facturas` (
  `id_facturas` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha` DATE NULL COMMENT '',
  `total` INT NULL COMMENT '',
  `tipo` VARCHAR(45) NULL COMMENT '',
  `ventas_id_venta` INT NOT NULL COMMENT '',
  `usuarios_id_usuario` INT NOT NULL COMMENT '',
  `clientes_id_clientes` INT NOT NULL COMMENT '',
  `iva_id_iva` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_facturas`)  COMMENT '',
  INDEX `fk_facturas_ventas1_idx` (`ventas_id_venta` ASC)  COMMENT '',
  INDEX `fk_facturas_usuarios1_idx` (`usuarios_id_usuario` ASC)  COMMENT '',
  INDEX `fk_facturas_clientes1_idx` (`clientes_id_clientes` ASC)  COMMENT '',
  INDEX `fk_facturas_iva1_idx` (`iva_id_iva` ASC)  COMMENT '',
  CONSTRAINT `fk_facturas_ventas1`
    FOREIGN KEY (`ventas_id_venta`)
    REFERENCES `sigi`.`ventas` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facturas_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `sigi`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facturas_clientes1`
    FOREIGN KEY (`clientes_id_clientes`)
    REFERENCES `sigi`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facturas_iva1`
    FOREIGN KEY (`iva_id_iva`)
    REFERENCES `sigi`.`iva` (`id_iva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`calendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`calendario` (
  `id_calendario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` VARCHAR(45) NULL COMMENT '',
  `fecha_alta` DATE NULL COMMENT '',
  `fecha_evento` DATE NULL COMMENT '',
  `fecha_previo` DATE NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `id_usuario` INT NULL COMMENT '',
  `usuarios_afectados` INT NULL COMMENT '',
  PRIMARY KEY (`id_calendario`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`locales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`locales` (
  `id_locales` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha_alta` DATE NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `direccion` VARCHAR(45) NULL COMMENT '',
  `telefono` INT NULL COMMENT '',
  `centro_costo` INT NULL COMMENT '',
  `id_gerente` INT NULL COMMENT '',
  PRIMARY KEY (`id_locales`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`sip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`sip` (
  `id_sip` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ultimo_conteo` DATE NULL COMMENT '',
  `id_usuario` INT NULL COMMENT '',
  `proximo_conteo` DATE NULL COMMENT '',
  `id_sector` INT NULL COMMENT '',
  `id_articulo` INT NULL COMMENT '',
  `cantidad_base` INT NULL COMMENT '',
  `cantidad_conteo` INT NULL COMMENT '',
  `observacion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_sip`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`locales_gastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`locales_gastos` (
  `id_gastos` INT NOT NULL COMMENT '',
  `fecha` DATE NULL COMMENT '',
  `total` INT NULL COMMENT '',
  `forma_pago` VARCHAR(45) NULL COMMENT '',
  `cc` VARCHAR(45) NULL COMMENT '',
  `locales_id_locales` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_gastos`)  COMMENT '',
  INDEX `fk_locales_gastos_locales1_idx` (`locales_id_locales` ASC)  COMMENT '',
  CONSTRAINT `fk_locales_gastos_locales1`
    FOREIGN KEY (`locales_id_locales`)
    REFERENCES `sigi`.`locales` (`id_locales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigi`.`precio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigi`.`precio` (
  `id_precio` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha` DATE NULL COMMENT '',
  `costo` INT NULL COMMENT '',
  `ultimo_precio` INT NULL COMMENT '',
  `nuevo_precio` INT NULL COMMENT '',
  `ganancia_por_unidad` INT NULL COMMENT '',
  `articulos_id_articulo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_precio`)  COMMENT '',
  INDEX `fk_precio_articulos1_idx` (`articulos_id_articulo` ASC)  COMMENT '',
  CONSTRAINT `fk_precio_articulos1`
    FOREIGN KEY (`articulos_id_articulo`)
    REFERENCES `sigi`.`articulos` (`id_articulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `sigi` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `sigi`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
