/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sigi;

import Connection.Conexion;
import java.sql.ResultSet;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.Doc;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintException;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import java.util.ArrayList;    //Para exportar e importar
import java.util.List;     //Para exportar e importar
import javax.swing.JTable;
/**
 *
 * @author Gustavo
 */
public class abmclientes extends javax.swing.JInternalFrame {
    Conexion con,query;
    ResultSet rs;
    ResultSet rs2;
    ResultSet rs3;
    static float total=0;
    static int j=0;
    static String aux3;
    static String result;
    static String inv[]=new String[50000];
    static float invT=0;
    public static String id,cad,id_sect, rstring;
    String hora,minutos,segundos,ampm;
    Calendar calendario;    
    public static int rowCount, numfac, rs1;
    public static boolean estado;


 private static DefaultTableModel modelo;

//para exportar
    private JFileChooser FileChooser = new JFileChooser();
    private Vector columna = new Vector();
    private Vector filas = new Vector();
    private static int tabla_ancho = 0;
    private static int tabla_alto = 0;
    public abmclientes() {
        initComponents();
        searchUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jTnomb_clien = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jTapell_clie = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jTnac_dia = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jTnac_mes = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jTnac_año = new javax.swing.JTextField();
        jTcel_clie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jTdirec_clie = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jCactivo_clie = new javax.swing.JCheckBox();
        jCpagdiferido = new javax.swing.JCheckBox();
        jLabel56 = new javax.swing.JLabel();
        jTmail_clie = new javax.swing.JTextField();
        jBcrea_clie = new javax.swing.JButton();
        jbcancelar = new javax.swing.JButton();
        jBmodifi_clie = new javax.swing.JButton();
        jBmodifi_clie1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        searchUser = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jTelefono_clie = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel57.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel57.setText("Buscar por nombre");

        jLabel47.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel47.setText("Nombre");

        jLabel48.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel48.setText("Apellido");

        jLabel55.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel55.setText("Cel.");

        jLabel49.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel49.setText("Fecha de nacimiento");

        jLabel52.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel52.setText("DD");

        jLabel51.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel51.setText("MM");

        jLabel50.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel50.setText("AAAA");

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel4.setText("/");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel3.setText("/");

        jLabel53.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel53.setText("Dirección");

        jLabel54.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel54.setText("Estados");

        jCactivo_clie.setBackground(new java.awt.Color(255, 255, 255));
        jCactivo_clie.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jCactivo_clie.setText("Activo");

        jCpagdiferido.setBackground(new java.awt.Color(255, 255, 255));
        jCpagdiferido.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jCpagdiferido.setText("Cuenta corriente");

        jLabel56.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel56.setText("Mail");

        jBcrea_clie.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jBcrea_clie.setText("Crear");
        jBcrea_clie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcrea_clieActionPerformed(evt);
            }
        });

        jbcancelar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jbcancelar.setText("Cancelar");
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });

        jBmodifi_clie.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jBmodifi_clie.setText("Modificar");
        jBmodifi_clie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodifi_clieActionPerformed(evt);
            }
        });

        jBmodifi_clie1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jBmodifi_clie1.setText("Eliminar");

        jButton1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jButton1.setText("A XLS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        searchUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchUserKeyReleased(evt);
            }
        });

        jLabel58.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel58.setText("Telefono");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel57)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchUser))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBcrea_clie, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbcancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBmodifi_clie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBmodifi_clie1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTelefono_clie, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTmail_clie, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel56, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel55, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTdirec_clie, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel53, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTcel_clie, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTapell_clie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTnomb_clien, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel51)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel50))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTnac_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jTnac_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTnac_año, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel54)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCactivo_clie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCpagdiferido)))
                        .addGap(208, 208, 208))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel47)
                        .addGap(9, 9, 9)
                        .addComponent(jTnomb_clien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTapell_clie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTelefono_clie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCactivo_clie)
                            .addComponent(jCpagdiferido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel49)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel52)
                            .addComponent(jLabel51)
                            .addComponent(jLabel50))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTnac_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jTnac_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTnac_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(11, 11, 11)
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTcel_clie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTdirec_clie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel56)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTmail_clie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcrea_clie, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBmodifi_clie, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBmodifi_clie1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(332, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcrea_clieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcrea_clieActionPerformed
        //BOTON PARA AGREGAR UN PRODUCTO A LA BASE DE DATOS

        int aux=0;

        // validaciones para saber que no se deja algun campo en limpio
        if (jTnomb_clien.getText().equals("")||jTapell_clie.getText().equals("")||jTdirec_clie.getText().equals("")
            ||jTcel_clie.getText().equals("")||jTmail_clie.getText().equals("")||jTnac_año.getText().equals("")||jTnac_mes.getText().equals("")||jTnac_dia.getText().equals(""))
        {

            JOptionPane.showMessageDialog(null, "Faltan Datos: No Puede Dejar Cuadros en Blanco");

        }

        else

        {
            try {
                // se comienza la conexion con la base de datos
                try {
                    con = new Conexion();

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(abmclientes.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(abmclientes.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(abmclientes.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(abmclientes.class.getName()).log(Level.SEVERE, null, ex);
                }

                String nombre = jTnomb_clien.getText();
                String apellido = jTapell_clie.getText();
                String direccion = jTdirec_clie.getText();
                String telefono = jTelefono_clie.getText();
                String cel = jTcel_clie.getText();
                String mail = jTmail_clie.getText();
                String nacimiento = jTnac_año.getText()+"-"+jTnac_mes.getText()+"-"+jTnac_dia.getText();
                boolean activo = jCactivo_clie.isSelected();
                String activo1 = Boolean.toString(activo);
                int activo2 = activo ? 1 : 0;
                boolean dif = jCpagdiferido.isSelected();
                String dif1 = Boolean.toString(dif);
                int dif2 = dif ? 1 : 0;
                String sql = "INSERT INTO `clientes`(`nombre`,`apellido`, `direccion`, `celular`,`mail`,`fecha_nac`, `activo`, `ctacte`) VALUES ('"+nombre+"','"+apellido+"','"+direccion+"','"+cel+"','"+mail+"','"+nacimiento+"','"+activo2+"','"+dif2+"')";
                con.ejecutar(sql);

                JOptionPane.showMessageDialog(null, "Cliente: "+nombre+", "+apellido+" agregado.");
                clearFields();

            } catch (SQLException ex) {
                Logger.getLogger(abmclientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBcrea_clieActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed
        clearFields();
    }//GEN-LAST:event_jbcancelarActionPerformed

    private void jBmodifi_clieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodifi_clieActionPerformed
        //BOTON PARA MODIFICAR LOS DATOS DE UN PRODUCTO EN LA BASE DE DATOS

        // validaciones para saber que no se deja algun campo en limpio
         if (jTnomb_clien.getText().equals("")||jTapell_clie.getText().equals("")||jTdirec_clie.getText().equals("")
            ||jTcel_clie.getText().equals("")||jTmail_clie.getText().equals("")||jTnac_año.getText().equals("")||jTnac_mes.getText().equals("")||jTnac_dia.getText().equals(""))
        {

            JOptionPane.showMessageDialog(null, "Faltan Datos: No Puede Dejar Cuadros en Blanco");

        }

        else

        {
            // por si se da clic antes de hacer la busqueda
            // se validan los textfield
                //String nombapell= jTbuscar_clie.getText();
                String nombre = jTnomb_clien.getText();
                String apellido = jTapell_clie.getText();
                String direccion = jTdirec_clie.getText();
                String telefono = jTelefono_clie.getText();
                //String prov_apell = jTprov_apell.getText();
                String cel = jTcel_clie.getText();
                String mail = jTmail_clie.getText();
                String nacimiento = jTnac_año.getText()+"-"+jTnac_mes.getText()+"-"+jTnac_dia.getText();
                //Para pasar el estado a string del CKBOX a la base SQL, responde FALSE o TRUE
                boolean activo = jCactivo_clie.isSelected();
                String activo1 = Boolean.toString(activo);
                //Pasa un entero 1 o 0 respectivamente
                int activo2 = activo ? 1 : 0;

                boolean dif = jCpagdiferido.isSelected();
                String dif1 = Boolean.toString(dif);
                //Pasa un entero 1 o 0 respectivamente
                int dif2 = dif ? 1 : 0;
                //      String marca = jTmarca.getText();
                //      String se   ctor = jTsector.getText();

            try {
                //se crea la conexion y las consultas
                con = new Conexion();
                //String sql ="SELECT id_clientes FROM productos WHERE nombre LIKE '%"+nombapell+"%'";
                int id2 = Integer.parseInt(id);
                // se crea la sentecia sql y se ejecuta para hacer la modificacion

                String modifica = "UPDATE `clientes` SET `nombre`='"+nombre+"',`apellido`='"+apellido+"',`direccion`='"+direccion+"',`celular`='"+cel+"',`mail`='"+mail+"',`fecha_nac`='"+nacimiento+"',`activo`='"+activo2+"',`ctacte`='"+dif2+"' WHERE id_clientes = '"+id2+"'";
                con.ejecutar(modifica);
                JOptionPane.showMessageDialog(null, "Datos Actualizados");

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(abmclientes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(abmclientes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(abmclientes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(abmclientes.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jBmodifi_clieActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser dialog = new JFileChooser();
        int opcion = dialog.showSaveDialog(abmclientes.this);

        if (opcion == JFileChooser.APPROVE_OPTION) {

            File dir = dialog.getSelectedFile();

            try {
                List<JTable> tb = new ArrayList<JTable>();
                //tb.add(jTtabla_clie);
                //-------------------
                export_excel excelExporter = new export_excel(tb, new File(dir.getAbsolutePath() + ".xls"));
                if (excelExporter.export()) {
                    JOptionPane.showMessageDialog(null, "TABLAS EXPORTADOS CON EXITOS!");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchUserKeyReleased
        int evento=evt.getKeyCode();
        String nom = searchUser.getText();
                 
        if(evento==10 ){
            String bool;
            try {
                    // se comienza la conexion con la base de datos
                    try {
                        con = new Conexion();

                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(abmclientes.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(abmclientes.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                        Logger.getLogger(abmclientes.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(abmclientes.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    
                    String [] stringParts = nom.split(",");
                    String name = stringParts[0];
                    String sql ="SELECT * FROM clientes WHERE nombre LIKE '"+name+"%'";
                    rs = con.Consulta(sql);
                    
                    if(rs == null) {
                       JOptionPane.showMessageDialog(null, "No se encontro el proveedor: "+searchUser.getText()+" ");
                    }
                    while(rs.next()){
                       
                        id =  rs.getString("id_clientes");
                        this.jTnomb_clien.setText(rs.getString("nombre"));
                        this.jTapell_clie.setText(rs.getString("apellido"));
                        this.jTdirec_clie.setText(rs.getString("direccion"));
                        this.jTmail_clie.setText(rs.getString("mail"));
                        this.jTelefono_clie.setText(rs.getString("telefono"));
                        this.jTcel_clie.setText(rs.getString("celular"));
                        if(rs.getInt("activo") == 1) {
                            bool = "true";
                        } else {
                            bool = "false";
                        }
                        String bool1 = bool;
                        boolean bool2 = Boolean.parseBoolean(bool1);
                        if(bool2==true){
                            jCactivo_clie.setSelected(true);
                        }else{
                            jCactivo_clie.setSelected(false);
                        }
                        String birth = rs.getString("fecha_nac");
                        String [] date = birth.split("-");
                        String anio = date[0];
                        String mes = date[1];
                        String dia = date[2];
                        jTnac_año.setText(anio);
                        jTnac_mes.setText(mes);
                        jTnac_dia.setText(dia);
                        if(rs.getInt("ctacte") == 1){
                            bool = "true";
                        }else {
                            bool = "false";
                        }
                        String bool3 = bool;
                        boolean bool4 = Boolean.parseBoolean(bool3);
                        if(bool4==true){
                           jCpagdiferido.setSelected(true);
                        }else{
                           jCpagdiferido.setSelected(false);
                        }
                    }

                    } catch (SQLException ex) {
                        Logger.getLogger(proveedores.class.getName()).log(Level.SEVERE, null, ex);
                    }
         
            }
    }//GEN-LAST:event_searchUserKeyReleased
    public void searchUsers(){
        try {
            // se comienza la conexion con la base de datos
            try {
                con = new Conexion();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(abmclientes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(abmclientes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(abmclientes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(abmclientes.class.getName()).log(Level.SEVERE, null, ex);
            }

            TextAutoCompleter textAutoAcompleter = new TextAutoCompleter(searchUser);
            String sql ="SELECT nombre, apellido FROM clientes";
            rs = con.Consulta(sql);
            while(rs.next()){
                String nombreApellido = rs.getString("nombre")+", "+rs.getString("apellido");
                result = nombreApellido;
                textAutoAcompleter.addItem(result);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(proveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void clearFields(){
        jTnomb_clien.setText("");
        jTapell_clie.setText("");
        jTdirec_clie.setText("");
        jTelefono_clie.setText("");
        jTcel_clie.setText("");
        jTmail_clie.setText("");
        jTnac_año.setText("");
        jTnac_mes.setText("");
        jTnac_dia.setText("");
        jCactivo_clie.setSelected(false);
        jCpagdiferido.setSelected(false);
    }

    public void CrearTabla(File file) throws IOException {

        Workbook workbook = null;
        modelo = new DefaultTableModel();
        
        modelo.addColumn("nombre");
        modelo.addColumn("apellido");
        modelo.addColumn("direccion");
        modelo.addColumn("mail");
        modelo.addColumn("telefono");
        modelo.addColumn("celular");
        modelo.addColumn("fecha_alta");
        modelo.addColumn("fecha_nac");
        modelo.addColumn("activo");
        modelo.addColumn("ctacte");
        //this.jTtabla_clie.setModel(modelo);
        try {
            workbook = Workbook.getWorkbook(file);

            Sheet sheet = workbook.getSheet(0);
            columna.clear();

            for (int i = 0; i < sheet.getColumns(); i++) {
                Cell cell1 = sheet.getCell(i, 0);
                columna.add(cell1.getContents());
            }
            filas.clear();

            for (int j = 1; j < sheet.getRows(); j++) {

                Vector d = new Vector();

                for (int i = 0; i < sheet.getColumns(); i++) {

                    Cell cell = sheet.getCell(i, j);
                    d.add(cell.getContents());
                }
                d.add("\n");
                //filas.add(d);
                modelo.addRow(d);
            }
    
        } catch (BiffException e) {
            e.printStackTrace();
        } 
}  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcrea_clie;
    private javax.swing.JButton jBmodifi_clie;
    private javax.swing.JButton jBmodifi_clie1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCactivo_clie;
    private javax.swing.JCheckBox jCpagdiferido;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTapell_clie;
    private javax.swing.JTextField jTcel_clie;
    private javax.swing.JTextField jTdirec_clie;
    private javax.swing.JTextField jTelefono_clie;
    private javax.swing.JTextField jTmail_clie;
    private javax.swing.JTextField jTnac_año;
    private javax.swing.JTextField jTnac_dia;
    private javax.swing.JTextField jTnac_mes;
    private javax.swing.JTextField jTnomb_clien;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JTextField searchUser;
    // End of variables declaration//GEN-END:variables
}
