/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sigi;
import Connection.Conexion;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.Doc;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintException;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import sigi.ModuloVenta;
import static sigi.Proveedores.id1;
/**
 *
 * @author Gustavo
 */
public class BajaArticulos extends javax.swing.JFrame {
Conexion con,query;
    ResultSet rs;
    ResultSet rs2;
    ResultSet rs3;
   static float total=0;
   static int j=0;
   public static int id1;
   public static String id;
    private static ModuloVenta myInstance;
    /**
     * Creates new form ArticEliminar
     */
    public BajaArticulos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTvscaningv = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBeliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTvscaningv.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jTvscaningv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTvscaningvActionPerformed(evt);
            }
        });
        jTvscaningv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTvscaningvKeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jBeliminar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jBeliminar.setText("Eliminar");
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel1.setText("Ingresar Codigo de producto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBeliminar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTvscaningv, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTvscaningv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jBeliminar)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTvscaningvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTvscaningvActionPerformed

    }//GEN-LAST:event_jTvscaningvActionPerformed

    private void jTvscaningvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTvscaningvKeyPressed

        try {
            // se comienza la conexion con la base de datos
            try {
                con = new Conexion();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(BajaArticulos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(BajaArticulos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(BajaArticulos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(BajaArticulos.class.getName()).log(Level.SEVERE, null, ex);
            }

            String nom= jTvscaningv.getText();
            String sql ="SELECT * FROM descripcion_articulos WHERE scanning LIKE '"+nom+"%' AND unidad > 0";
            rs = con.Consulta(sql);

            if(rs==null)
            JOptionPane.showMessageDialog(null, "No se encontro el scanning: "+jTvscaningv.getText()+" en la base de datos.");

            //prueba 1

            // fin prueba

            //Para establecer el modelo al JTable

            DefaultTableModel buscar = new DefaultTableModel(){
                @Override
                public boolean isCellEditable(int rowIndex, int vColIndex) {
                    return false;
                }};
                this.jTable1.setModel(buscar);
                buscar.addColumn("ID");
                buscar.addColumn("Nombre Producto");
                buscar.addColumn("Precio");
                buscar.addColumn("Cantidad");
                int y=0;
                while (rs.next()) {
                    Object[] fila = new Object[4];
                    fila[0] = rs.getInt("id_articulo");    
                    fila[1] = rs.getString("nombre_producto");
                    fila[2] = rs.getDouble("precio_venta");
                    fila[3] = rs.getInt("unidad");
                    buscar.addRow(fila); // Añade una fila al final del modelo de la tabla
                }

            } catch (SQLException ex) {
                Logger.getLogger(ModuloVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                jTvscaningv.requestFocusInWindow();
                jTable1.selectAll();
               
            }
    }//GEN-LAST:event_jTvscaningvKeyPressed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
         int evento=evt.getKeyCode();
        
        if(evento==10 ){
            //DefaultTableModel modelo = new DefaultTableModel();
            //        this.Tlista.setModel(modelo);

            DefaultTableModel modelo = new DefaultTableModel(){
                @Override
                public boolean isCellEditable(int rowIndex, int vColIndex) {
                    return false;
                }};

                int aux = jTable1.getSelectedRow();
                if (aux==-1)
                {

                    JOptionPane.showMessageDialog(null, "No se a seleccionado nada de la tabla.");

                }
String bool;
        int Opcion=this.jTable1.getSelectedRow();
        //muestra el no. de renglon
        // JOptionPane.showMessageDialog(rootPane,Opcion);
        id =  jTable1.getValueAt(Opcion,0).toString();
         
            }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed

        try {
            // se comienza la conexion con la base de datos
            try {
                con = new Conexion();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(BajaArticulos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(BajaArticulos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(BajaArticulos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(BajaArticulos.class.getName()).log(Level.SEVERE, null, ex);
            }
            //sentencias sql para insertar los datos en la base de datos
            String sql = "DELETE FROM `descripcion_articulos` WHERE id_articulo='"+id+"'";

            //funcion para ejecutar la query
            con.ejecutar(sql);

            JOptionPane.showMessageDialog(null, "Articulo eliminado.");

            //se obtienen los datos especificos de la consulta

            //se limpian los campos de texto para seguir agregando mas datos
            
            jTvscaningv.setText("");
            jTable1.setModel(new DefaultTableModel());

        } catch (SQLException ex) {
            Logger.getLogger(BajaArticulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBeliminarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int rowIndex, int vColIndex) {
                return false;
            }};
            int aux = jTable1.getSelectedRow();
            if (aux==-1){
                JOptionPane.showMessageDialog(null, "No se a seleccionado nada de la tabla.");
            }
        int Opcion=this.jTable1.getSelectedRow();
        id =  jTable1.getValueAt(Opcion,0).toString();
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BajaArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BajaArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BajaArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BajaArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BajaArticulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBeliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTvscaningv;
    // End of variables declaration//GEN-END:variables
}
