/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sigi;

import javax.swing.JOptionPane;
import Connection.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author diego
 */
public class CierreCaja extends javax.swing.JFrame {
    Conexion con;
    ResultSet rs;
    ResultSet rs2;
    
    String userId = Integer.toString(Login.userId);

    public CierreCaja() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cierreX = new javax.swing.JButton();
        cierreZ = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        cierreX.setText("CIERRE (X)");

        cierreZ.setText("CIERRE (Z)");
        cierreZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cierreZActionPerformed(evt);
            }
        });

        cerrar.setText("CERRAR");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de cierre (X) es para cierre provisional.");

        jLabel2.setText("Tipo de cierre (Z) es para hacer el cierre del día.");

        jLabel3.setText("TIPOS DE CIERRE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cierreX, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cierreZ, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cierreZ, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cierreX, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        moduloVenta abrir = new moduloVenta();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void cierreZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cierreZActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Seguro que desea realizar el cierre Z", "Cierre", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        if(option == JOptionPane.YES_OPTION){
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            Date date = new Date();
            String initialDate = dateFormat.format(date);
            String closeSales = JOptionPane.showInputDialog("Monto total en la caja", "0");
            float closeSalesValue = Float.parseFloat(closeSales);
            if(closeSalesValue > 0){
            try {
                try {
                    con = new Conexion();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CierreCaja.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(CierreCaja.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(CierreCaja.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(CierreCaja.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                String cantidadEstimada = "SELECT SUM(total) suma_total FROM ventas WHERE fecha > DATE_FORMAT(NOW(),'%Y-%m-%d 00:00:00') AND fecha < CURRENT_TIME";
                float cant = 0;
                  //  String cierre= closeSales;
                //    String apertura ="INSERT INTO  `sigi`.`caja` (`cierre`, `id_usuario`)VALUES ('"+closeSalesValue+"', '"+userId+"')";
                    rs = con.Consulta(cantidadEstimada);
                    while(rs.next()) {
                        cant = rs.getFloat("suma_total");
                    }
                    if(cant == closeSalesValue) {
                        String ingresarCierre = "INSERT INTO cierreX (id_usuario, tickets, monto_estimado, monto_total, quebrantos) VALUES ()";
                    }
                    System.out.println(cant);
                    this.dispose();
                    ppalVendedor.jBvta.setEnabled(true);
                    ppal.jBvta.setEnabled(true);
                } catch (SQLException ex) {
                    Logger.getLogger(moduloVenta.class.getName()).log(Level.SEVERE, null, ex);
                }
                //this.dispose();
//                if(Login.userRol != 1) {
//                    ppalVendedor.jBvta.setEnabled(true); 
//                } else {
//                    ppal.jBvta.setEnabled(true); 
//                }
            } else {
                closeSales = "0";
                JOptionPane.showMessageDialog(null, "Debe ingresar el conteo de cierre de caja, intente nuevamente. ");
            }
        }
    }//GEN-LAST:event_cierreZActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar;
    private javax.swing.JButton cierreX;
    private javax.swing.JButton cierreZ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
