    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sigi;

import Connection.Conexion;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.Doc;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintException;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Gustavo
 */
public class moduloVenta extends javax.swing.JFrame {
    Conexion con;
    ResultSet rs;
    ResultSet rs2;

    String userRole = Integer.toString(Login.userRol);
    String userId = Integer.toString(Login.userId);
    static BigDecimal total = BigDecimal.ZERO;
    static int j = 0;
    public static String id1, id2;
    public String descuento = "0.00";
    public String cantidad = "1";
    static BigDecimal auxiliarTotal = BigDecimal.ZERO;
    static BigDecimal descuentoAuxiliar = BigDecimal.ZERO;
    static BigDecimal cantidadSolicitada = BigDecimal.ZERO;
    static BigDecimal getTotalVentas;
    String articleId = null;
    
    public moduloVenta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scanning = new javax.swing.JTextField();
        totalVentas = new javax.swing.JTextField();
        eliminarFila = new javax.swing.JButton();
        vender = new javax.swing.JButton();
        jBcerrar = new javax.swing.JButton();
        borrarTodo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        printTicket = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(880, 610));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scanning.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        scanning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scanningActionPerformed(evt);
            }
        });
        scanning.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                scanningKeyReleased(evt);
            }
        });
        getContentPane().add(scanning, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 390, 60));

        totalVentas.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        totalVentas.setForeground(new java.awt.Color(255, 0, 0));
        totalVentas.setText("0.00");
        getContentPane().add(totalVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 500, 60));

        eliminarFila.setBackground(new java.awt.Color(255, 255, 255));
        eliminarFila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminafila.jpg"))); // NOI18N
        eliminarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarFilaActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 60, 60));

        vender.setBackground(new java.awt.Color(231, 224, 224));
        vender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carritoVentas.png"))); // NOI18N
        vender.setBorderPainted(false);
        vender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderActionPerformed(evt);
            }
        });
        getContentPane().add(vender, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, 80, 60));

        jBcerrar.setBackground(new java.awt.Color(255, 255, 255));
        jBcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.jpg"))); // NOI18N
        jBcerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBcerrarMouseClicked(evt);
            }
        });
        jBcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 550, 60, 60));

        borrarTodo.setBackground(new java.awt.Color(255, 255, 255));
        borrarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel vta.jpg"))); // NOI18N
        borrarTodo.setBorderPainted(false);
        borrarTodo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarTodoActionPerformed(evt);
            }
        });
        getContentPane().add(borrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 60, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SCANING");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Marca", "Precio", "Cantidad", "Descuento", "Cantidad venta", "Cantidad stock", "Tipo articulo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane18.setViewportView(tablaCompras);
        if (tablaCompras.getColumnModel().getColumnCount() > 0) {
            tablaCompras.getColumnModel().getColumn(0).setResizable(false);
            tablaCompras.getColumnModel().getColumn(1).setResizable(false);
            tablaCompras.getColumnModel().getColumn(2).setResizable(false);
            tablaCompras.getColumnModel().getColumn(3).setResizable(false);
            tablaCompras.getColumnModel().getColumn(4).setResizable(false);
            tablaCompras.getColumnModel().getColumn(5).setResizable(false);
            tablaCompras.getColumnModel().getColumn(6).setMinWidth(0);
            tablaCompras.getColumnModel().getColumn(6).setPreferredWidth(0);
            tablaCompras.getColumnModel().getColumn(6).setMaxWidth(0);
            tablaCompras.getColumnModel().getColumn(7).setMinWidth(0);
            tablaCompras.getColumnModel().getColumn(7).setPreferredWidth(0);
            tablaCompras.getColumnModel().getColumn(7).setMaxWidth(0);
            tablaCompras.getColumnModel().getColumn(8).setMinWidth(0);
            tablaCompras.getColumnModel().getColumn(8).setPreferredWidth(0);
            tablaCompras.getColumnModel().getColumn(8).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 850, 310));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("$");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("COMPRA ACTUAL");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jButton4.setText("Cta Cte");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 80, 60));

        printTicket.setText("Imprimit ticket");
        getContentPane().add(printTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 160, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBcerrarMouseClicked
        CierreCaja tipoCierre = new CierreCaja();
        tipoCierre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBcerrarMouseClicked

    
    private void eliminarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarFilaActionPerformed
        DefaultTableModel eliminarFilaModel = (DefaultTableModel)tablaCompras.getModel();
        int fila = tablaCompras.getSelectedRow();
        BigDecimal restarDescuento = new BigDecimal(tablaCompras.getValueAt(fila, 5).toString());
        int restarTipo = Integer.parseInt(tablaCompras.getValueAt(fila, 8).toString());
        BigDecimal restarPrecio = new BigDecimal(tablaCompras.getValueAt(fila, 3).toString());
        float restarCantidad;
        if(restarTipo == 1) {
            restarCantidad = Float.parseFloat(tablaCompras.getValueAt(fila, 6).toString());
        } else {
            restarCantidad = Float.parseFloat(tablaCompras.getValueAt(fila, 6).toString()) * 1000;
        }
        auxiliarTotal = restarPrecio;
        cantidadSolicitada = new BigDecimal(restarCantidad);
        auxiliarTotal = auxiliarTotal.multiply(cantidadSolicitada).setScale(2, RoundingMode.CEILING);
        total = total.subtract(auxiliarTotal).subtract(restarDescuento).setScale(2, RoundingMode.CEILING);
        String totalAString = String.valueOf(total);
        totalVentas.setText(totalAString);
        if(fila < 0) {
            JOptionPane.showMessageDialog(null, "Se debe seleccionar la fila a eliminar de la tabla COMPRA ACTUAL");
        } else{
            eliminarFilaModel.removeRow(fila);           
        }
        scanning.setText("");
        scanning.requestFocus();
        j = fila - 1;
    }//GEN-LAST:event_eliminarFilaActionPerformed

    private void borrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarTodoActionPerformed
        total = BigDecimal.ZERO;
        totalVentas.setText("0.00");
        descuento = "0.00";
        cantidad = "1";
        scanning.setText("");                
        scanning.requestFocus();
        System.out.println("eliminarTodo: " + tablaCompras.getRowCount());
        DefaultTableModel eliminarTodo = (DefaultTableModel) tablaCompras.getModel();
        eliminarTodo.setRowCount(0);
        j = 0;
    }//GEN-LAST:event_borrarTodoActionPerformed

    private void venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderActionPerformed

        String ticket = "";
        String ticketToByte;
        String ticketNumber = "";
        if(j==0) {
            JOptionPane.showMessageDialog(null, "No hay ningun elemento  en la Tabla de Venta");
        } else {
            try {
                con = new Conexion();
                String nombreProducto [] = new String[j], marcaProducto [] = new String[j];
                float cantidadVenta[] = new float[j];                
                float cantidadStock[] = new float[j];
                BigDecimal precioVenta[] = new BigDecimal[j];
                String scanningArticulo[] = new String[j];
                int tipoArticulo[] = new int[j];
                float nuevoStock;

                for (int i=0; i<j; i++) {
                    scanningArticulo[i] = tablaCompras.getValueAt(i, 0).toString();
                    nombreProducto[i] = tablaCompras.getValueAt(i, 1).toString();
                    marcaProducto[i] = tablaCompras.getValueAt(i, 2).toString();
                    precioVenta[i]= new BigDecimal(tablaCompras.getValueAt(i, 3).toString());
                    cantidadStock[i] = Float.parseFloat(tablaCompras.getValueAt(i, 7).toString());
                    tipoArticulo[i] = Integer.parseInt(tablaCompras.getValueAt(i, 8).toString());
                    if(tipoArticulo[i] == 1) {
                        cantidadVenta[i] = Float.parseFloat(tablaCompras.getValueAt(i, 6).toString());
                    } else {
                        cantidadVenta[i] = Float.parseFloat(tablaCompras.getValueAt(i, 6).toString()) * 1000;
                    }
                    nuevoStock = cantidadStock[i] - cantidadVenta[i];
                    int guardarStock = (int)nuevoStock;
                    String modifica = "UPDATE stock SET saldo_stock = "+guardarStock+" WHERE id_articulo ="+articleId+"";
                    con.ejecutar(modifica);
                }
                getTotalVentas = new BigDecimal(totalVentas.getText());
                String user = "SELECT * FROM usuarios WHERE Id_usuario= '"+userId+"'";
                String nombre = null, apellido = null;
                rs = con.Consulta(user);
                while(rs.next()){
                    nombre = rs.getString(2);
                    apellido = rs.getString(3);
                }
                String venta = "INSERT INTO ventas (fecha, id_usuario, total, descuento, forma_pago_id_forma_pago, iva_id_iva)VALUES (CURRENT_TIMESTAMP, '"+userId+"', '"+getTotalVentas+"', '"+descuento+"', 1, NULL);";
                
                con.ejecutar(venta);
                
                String getIdVenta = "SELECT LAST_INSERT_ID() AS id_venta";
                int id = 0;
                rs = con.Consulta(getIdVenta);
                while(rs.next()){
                    id = rs.getInt("id_venta");
                    id1 = Integer.toString(id);
                }
                for(int i=0;i<j;i++){
                    venta = "INSERT INTO sigi.detalle_venta (scanning, precio, cantidad, fecha, id_usuario, ventas_id_venta) VALUES ('"+scanningArticulo[i]+"', '"+precioVenta[i]+"', '"+cantidadVenta[i]+"', CURRENT_TIMESTAMP, '"+userId+"', '"+id1+"');";
                    con.ejecutar(venta);
                }
                Date fecha = new Date();
                String efectivo = JOptionPane.showInputDialog(null, "Venta Realizada\nTotal a Cobrar: $"+getTotalVentas+"\nEfectivo Recibido: ");
                String cadena = "Kiosco Minimarket 'La esquina'\nCUIL: xx-xxxxxxxx-x\nTicket NÂ°: "+ticketNumber+"\nSu dirección N° \nMendoza \nFecha: "+fecha+"\n\n";
                String cade="";
                for (int i=0;i<j;i++){
                    if(scanningArticulo[i].length()<=8){
                        scanningArticulo[i] = scanningArticulo[i]+"     ";
                    }
                    if(scanningArticulo[i].length() > 15){
                        scanningArticulo[i] = scanningArticulo[i].substring(0, 15);
                    }
                    cade = cade+""+cantidadVenta[i]+" x "+precioVenta[i]+"\n"+scanningArticulo[i].substring(0, 5)+" "+nombreProducto[i]+" "+marcaProducto[i].substring(0, 5)+"\t"+precioVenta[i].multiply(new BigDecimal(cantidadVenta[i])).setScale(2, RoundingMode.CEILING)+"\n";
                }
                if(efectivo != null) {
                    BigDecimal pagoEfectivo = new BigDecimal(efectivo);
                    BigDecimal cambio = pagoEfectivo.subtract(getTotalVentas).setScale(2, RoundingMode.CEILING);
                    if(printTicket.isSelected()) {
                        if(descuento != null) {
                            ticket = cadena+cade+"\nTOTAL: \t\t\t\t"+totalVentas.getText()+"\n\nEfectivo: \t\t\t"+efectivo+"\nDescuento: \t\t\t"+descuento+"\nCambio: \t\t\t"+cambio+"\n\nLe atendio: "+nombre+" "+apellido+"\n\nGRACIAS POR SU COMPRA.\n\n\n\n";
                        } else {
                            ticket = cadena+cade+"\nTOTAL: \t\t\t\t"+totalVentas.getText()+"\n\nEfectivo: \t\t\t"+efectivo+"\nCambio: \t\t\t"+cambio+"\n\nLe atendio: "+nombre+" "+apellido+"\n\nGRACIAS POR SU COMPRA.\n\n\n\n";
                        }
                        //Cogemos el servicio de impresion por defecto (impresora por defecto)
                        PrintService service = PrintServiceLookup.lookupDefaultPrintService();
                        //Le decimos el tipo de datos que vamos a enviar a la impresora
                        //Tipo: bytes Subtipo: autodetectado
                        DocFlavor flavor = DocFlavor.BYTE_ARRAY.AUTOSENSE;
                        //Creamos un trabajo de impresion
                        DocPrintJob pj = service.createPrintJob();
                        //Nuestro trabajo de impresion envia una cadena de texto
                        ticketToByte = ticket;
                        byte[] bytes;
                        //Transformamos el texto a bytes que es lo que soporta la impresora
                        bytes = ticketToByte.getBytes();
                        //Creamos un documento (Como si fuese una hoja de Word para imprimir)
                        Doc doc=new SimpleDoc(bytes,flavor,null);
                        //PrintRequestAttributeSet aset = new HashPrintRequestHashAttributeSet();
                        //aset.add(MediaSizeName.ISO_A4);
                        //Obligado coger la excepcion PrintException
                        //Mandamos a impremir el documento
                        System.out.println(ticket);
                        PrintService[] pservices =PrintServiceLookup.lookupPrintServices(flavor, null);
                        pj.print(doc, null);
                        ticket = "";
                    }
                    JOptionPane.showMessageDialog(null, "Venta Realizada\n\nTotal a Cobrar: $"+getTotalVentas+"\nCambio: $"+cambio);
                    total = BigDecimal.ZERO;
                    scanning.setText("");                
                    scanning.requestFocus();
                    totalVentas.setText("0.00");
                    descuento = "0.00";
                    DefaultTableModel temp = (DefaultTableModel) tablaCompras.getModel();
                    temp.setRowCount(0);
                    j=0;
                }
            } catch (PrintException | ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException ex1) {
                Logger.getLogger(moduloVenta.class.getName()).log(Level.SEVERE, null, ex1);
            }

        }
    }//GEN-LAST:event_venderActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ctacte ctacte = new ctacte();
        ctacte.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void scanningKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_scanningKeyReleased
        this.setFocusable(true);
        if((evt.getKeyCode() == KeyEvent.VK_C) && ((evt.getModifiers() & KeyEvent.CTRL_MASK) != 0)) {
            String cantidadString = JOptionPane.showInputDialog("Cantidad", "0");
            if(cantidadString != null) {
                cantidad = cantidadString;
            }
        }
        if((evt.getKeyCode() == KeyEvent.VK_D) && ((evt.getModifiers() & KeyEvent.CTRL_MASK) != 0)) {
            String descuentoString = JOptionPane.showInputDialog("Descuento", "0.00");
            if(descuentoString != null) {
                descuento = descuentoString;
            }
        }
        if((evt.getKeyCode() == KeyEvent.VK_P) && ((evt.getModifiers() & KeyEvent.CTRL_MASK) != 0)) {
            String cantidadString = JOptionPane.showInputDialog("Cantidad", "0");
            if(cantidadString != null) {
                int cant = Integer.parseInt(cantidadString);
                float aux = (float)cant / 1000;
                cantidad = Float.toString(aux);
            }
        }
        try {
            try {
                con = new Conexion();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(moduloVenta.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(moduloVenta.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(moduloVenta.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(moduloVenta.class.getName()).log(Level.SEVERE, null, ex);
            }

            String searchScanning= scanning.getText();
            int tipo = 0;
            //String sql = "SELECT descripcion_articulos.id_articulo, descripcion_articulos.scanning, descripcion_articulos.nombre_producto, descripcion_articulos.marca, descripcion_articulos.precio_venta, descripcion_articulos.tipo_articulo_id, stock.saldo_stock FROM descripcion_articulos INNER JOIN stock ON stock.id_articulo = descripcion_articulos.id_articulo WHERE descripcion_articulos.scanning = '"+searchScanning+"%'";
            String sql = "SELECT descripcion_articulos.id_articulo, descripcion_articulos.scanning, descripcion_articulos.nombre_producto, descripcion_articulos.marca, descripcion_articulos.precio_venta, descripcion_articulos.tipo_articulo_id, stock.saldo_stock FROM descripcion_articulos INNER JOIN stock ON stock.id_articulo = descripcion_articulos.id_articulo WHERE descripcion_articulos.scanning = ?";
            rs = con.find(sql, searchScanning);
            //rs = con.Consulta(sql);
            if(rs==null) {
                JOptionPane.showMessageDialog(null, "No se encontro el scanning: "+scanning.getText()+" en la base de datos.");
            }
            String codigo = "";
            String nombre = "", marca = "";
            BigDecimal precio = BigDecimal.ZERO;
            BigDecimal cantidadEnStock = BigDecimal.ZERO;
            int numberOfRows = 0;
            while (rs.next()) {
                ++numberOfRows;
                articleId = rs.getString("id_articulo");
                tipo = rs.getInt("tipo_articulo_id");
                codigo = rs.getString("scanning");
                nombre = rs.getString("nombre_producto");
                marca = rs.getString("marca");
                precio = rs.getBigDecimal("precio_venta");
                cantidadEnStock = rs.getBigDecimal("saldo_stock");
            }
            if(numberOfRows == 1){
                descuentoAuxiliar = new BigDecimal(descuento);
                auxiliarTotal = precio;
                cantidadSolicitada = new BigDecimal(cantidad);
                String cantidadMostrar;
                if (cantidadSolicitada.compareTo(cantidadEnStock) == 1) {
                    JOptionPane.showMessageDialog(null, "Verificar stock para producto " + nombre);
                } else {
                    if(tipo == 2) {
                        float cantidadTipo = Float.parseFloat(cantidad);
                        float auxiliarTipo =  (float)cantidadTipo * 1000;
                        cantidad = Float.toString(cantidadTipo);
                        cantidadMostrar = Float.toString(auxiliarTipo) + " Gr.";
                    } else {
                        cantidadMostrar = cantidad + " Unid.";
                    }
                    //cantidadEnStock = cantidadEnStock.subtract(cantidadSolicitada);
                    auxiliarTotal = auxiliarTotal.multiply(cantidadSolicitada).setScale(2, RoundingMode.CEILING);
                    total = auxiliarTotal.add(total).subtract(descuentoAuxiliar).setScale(2, RoundingMode.CEILING);
                    String aux3 = String.valueOf(total);
                    totalVentas.setText(aux3);

                    DefaultTableModel temp = (DefaultTableModel) tablaCompras.getModel();

                    Object nuevo[] = {temp.getRowCount()+1,"",""};
                    temp.addRow(nuevo);
                    //descuento
                    tablaCompras.setValueAt(codigo, j, 0);
                    tablaCompras.setValueAt(nombre, j, 1);
                    tablaCompras.setValueAt(marca, j, 2);
                    tablaCompras.setValueAt(precio, j, 3);
                    tablaCompras.setValueAt(cantidadMostrar, j, 4);
                    tablaCompras.setValueAt(descuento, j, 5);
                    tablaCompras.setValueAt(cantidad, j, 6);
                    tablaCompras.setValueAt(cantidadEnStock, j, 7);
                    tablaCompras.setValueAt(tipo, j, 8);
                    j++;//Aumenta el contador
                }
                scanning.setText("");
                cantidad = "1";
                descuento = "0.00";
                scanning.requestFocus();
            }
        } catch (SQLException ex) {
            Logger.getLogger(moduloVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_scanningKeyReleased

    private void jBcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBcerrarActionPerformed

    private void scanningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scanningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scanningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(moduloVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(moduloVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(moduloVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(moduloVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new moduloVenta().setVisible(true);
            }
        });
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarTodo;
    private javax.swing.JButton eliminarFila;
    public javax.swing.JButton jBcerrar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JCheckBox printTicket;
    private javax.swing.JTextField scanning;
    private javax.swing.JTable tablaCompras;
    private javax.swing.JTextField totalVentas;
    private javax.swing.JButton vender;
    // End of variables declaration//GEN-END:variables
  
}
