package sigi;
import Connection.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.GregorianCalendar;

public class ppal extends javax.swing.JFrame {
    Conexion con,query;
    ResultSet rs;
    ResultSet rs2;
    ResultSet rs3;
    public  int IDusuario;
    String id2="";
    private int limite = 4;
    static int j=0,w=0,jj=0; 
    static String aux3;
    static float total=0;
    static String inv[]=new String[50000];
    static float invT=0;
    public static String id,cad,id_nota;
    String hora,minutos,segundos,ampm;
    Calendar calendario;    
    Thread h1;
    public static int rowCount, numfac;
    public static boolean ABM_Articulo;
    
    public ppal() {         
        initComponents();
        jLuserName.setText(Login.userName);
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);    

        Calendar fecha = new GregorianCalendar();
        int year = fecha.get(Calendar.YEAR);
        String year1 = Integer.toString(year);
        int month = (fecha.get(Calendar.MONTH)+1);
        String month1 = Integer.toString(month);
        int day = fecha.get(Calendar.DAY_OF_MONTH);
        String day1 = Integer.toString(day);
        String fechaact = year1+"-"+month1+"-"+day1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        desktopPane = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jBvta = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLuserName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ctacte = new javax.swing.JButton();
        lbHora1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));
        desktopPane.setForeground(new java.awt.Color(255, 255, 255));
        desktopPane.setMaximumSize(new java.awt.Dimension(1680, 960));
        desktopPane.setPreferredSize(new java.awt.Dimension(1024, 768));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Menu");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Articulos");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ABM Articulos");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Stock");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Compras");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ABM Compra");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("OC");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Buscar Facturas");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Ajustes");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Caja");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Venta");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Clientes");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ABM Cliente");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Proveedores");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ABM Proveedor");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Cuentas Corrientes");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Reportes");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Administrar BD");
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTree1.setRootVisible(false);
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTree1);

        jBvta.setBackground(new java.awt.Color(255, 255, 255));
        jBvta.setText("VTA");
        jBvta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBvta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBvta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBvta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBvtaMouseClicked(evt);
            }
        });
        jBvta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvtaActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info.jpg"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("USUARIO");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Modulos");

        ctacte.setText("ctacte");
        ctacte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctacteActionPerformed(evt);
            }
        });

        lbHora1.setText("HORA");

        jMenu1.setText("Modificar");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Contraseña");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Cerrar Sesión");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBvta, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton3)
                        .addGap(29, 29, 29)
                        .addComponent(ctacte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbHora1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLuserName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBvta, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctacte, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbHora1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLuserName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Compras objIC = new Compras();
    altaModificaionArticulos objIC1 = new altaModificaionArticulos();
    bajaArticulos objIC20=new bajaArticulos();
    AbmClientes objIC3=new AbmClientes();
    //abmusuario objIC4=new abmusuario();
    ajusteCaja objIC5=new ajusteCaja();
    ajusteVenta objIC6=new ajusteVenta();
    buscarfacturas objIC9=new buscarfacturas();
    cliente objIC10=new cliente();
    configsoft objIC11=new configsoft();
    ctacte objIC12=new ctacte();
    estadocuentas objIC13=new estadocuentas();
    importarexportar objIC15=new importarexportar();
    oc objIC16=new oc();
    permisos objIC17=new permisos();
    proveedores objIC19=new proveedores();
    reportes objIC26=new reportes();
    stock objIC25=new stock();
    backupbd objIC27 = new backupbd();

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        
        String menu = jTree1.getLastSelectedPathComponent().toString();
        if(menu.equals("ABM Compra")){
           if(objIC.isShowing()){
        	//mensaje de que está abierto si se desea
            }else{
                desktopPane.add(objIC);
                objIC.show();
                objIC.setSize(desktopPane.getSize());
            }
        } 
        if(menu.equals("ABM Articulos") ){
            if(objIC1.isShowing()){
                //mensaje de que está abierto si se desea
            }else{
                desktopPane.add(objIC1);
                objIC1.show();
                objIC1.setSize(desktopPane.getSize());
            }
        }
        if(menu.equals("ABM Cliente")){
            if(objIC3.isShowing()){
                //mensaje de que está abierto si se desea
            }else{
                desktopPane.add(objIC3);
                objIC3.show();
                objIC3.setSize(desktopPane.getSize());
            }
        } 
        if(menu.equals("Stock")){
            if(objIC25.isShowing()){
		//mensaje de que está abierto si se desea
            }else{
                desktopPane.add(objIC25);
                objIC25.show();
                objIC25.setSize(desktopPane.getSize());
            }
        }
        if(menu.equals("Cuentas Corrientes")){
            if(objIC12.isShowing()){
		//mensaje de que está abierto si se desea
            }else{
                desktopPane.add(objIC12);
                objIC12.show();
                objIC12.setSize(desktopPane.getSize());
            }
        }
        if(menu.equals("OC")){
            if(objIC16.isShowing()){
		//mensaje de que está abierto si se desea
            }else{
                desktopPane.add(objIC16);
                objIC16.show();
                objIC3.setSize(desktopPane.getSize());
            }
        } 
        if(menu.equals("ABM Proveedor")){
            if(objIC19.isShowing()){
		//mensaje de que está abierto si se desea
            }else{
                desktopPane.add(objIC19);
                objIC19.show();
                objIC19.setSize(desktopPane.getSize());
            }
        } 
        if(menu.equals("Permisos")){
            if(objIC17.isShowing()){
		//mensaje de que está abierto si se desea
            }else{
                desktopPane.add(objIC17);
                objIC17.show();
                //objIC17.setSize(desktopPane.getSize());
            }
        } 
        if(menu.equals("Buscar Facturas")){
            if(objIC9.isShowing()){
		//mensaje de que está abierto si se desea
            }else{
                desktopPane.add(objIC9);
                objIC9.show();
                //objIC17.setSize(desktopPane.getSize());
            }
        } 
        if(menu.equals("Caja")){
            if(objIC5.isShowing()){
		//mensaje de que está abierto si se desea
            }else{
                desktopPane.add(objIC5);
                objIC5.show();
                //objIC17.setSize(desktopPane.getSize());
            }
        }
        if(menu.equals("Reportes")){
            if(objIC26.isShowing()){
		//mensaje de que está abierto si se desea
            }else{
                desktopPane.add(objIC26);
                objIC26.show();
                objIC26.setSize(desktopPane.getSize());
            }
        }
        if(menu.equals("Administrar BD")){
            if(objIC27.isShowing()){
		//mensaje de que está abierto si se desea
            }else{
                desktopPane.add(objIC27);
                objIC27.show();
                objIC27.setSize(desktopPane.getSize());
            }
        }
    }//GEN-LAST:event_jTree1MouseClicked
    
    private void jBvtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvtaActionPerformed
 /*       
        moduloVenta vta = new moduloVenta();
         vta.setVisible(true);
       jBvta.setEnabled(false);*/
    }//GEN-LAST:event_jBvtaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
        AbmUsuario showAbmUser = new AbmUsuario();
         showAbmUser.setVisible(true);
      // jBvta.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ctacteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctacteActionPerformed
        ctacte showCtacte = new ctacte();
        showCtacte.setVisible(true);
    }//GEN-LAST:event_ctacteActionPerformed

    private void jBvtaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBvtaMouseClicked
        String openSales = JOptionPane.showInputDialog("Ingrese apertura caja: ", "0");
        float openSalesValue = Float.parseFloat(openSales);
        if(openSalesValue > 0){
//        try {
//            try {
//                con = new Conexion();
//            } catch (ClassNotFoundException ex) {
//                Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (SQLException ex) {
//                Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (InstantiationException ex) {
//                Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (IllegalAccessException ex) {
//                Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
//            }
//
//          
//            String apertura ="INSERT INTO  `sigi`.`caja` (`apertura`, `id_usuario`)VALUES ('"+openSalesValue+"', '"+Login.userId+"')";
//
//            con.ejecutar(apertura);
//
//            } catch (SQLException ex) {
//                Logger.getLogger(moduloVenta.class.getName()).log(Level.SEVERE, null, ex);
//            }
            queries("INSERT INTO  `sigi`.`caja` (`apertura`, `id_usuario`)VALUES ('"+openSalesValue+"', '"+Login.userId+"')");
            moduloVenta vta = new moduloVenta();
            vta.setVisible(true);
            jBvta.setEnabled(false);   
        } else {
            openSales = "0";
            JOptionPane.showMessageDialog(null, "Debe ingresar el conteo de apertura de caja, intente nuevamente. ");
        }
    }//GEN-LAST:event_jBvtaMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(JOptionPane.showConfirmDialog(rootPane, "Esta seguro de cerrar la sesion actual?","Cerrar sesión",1)==0){
            this.dispose();
            Login login = new Login();
            Dimension pantall = Toolkit.getDefaultToolkit().getScreenSize();  
            //obtenemos el tamaño de la ventana  
            Dimension ventan = login.getSize();  
            //para centrar la ventana lo hacemos con el siguiente calculo  
            login.setLocation((pantall.width - ventan.width) / 2, (pantall.height - ventan.height) / 2);
            login.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        modificar mod = new modificar();
        mod.id = IDusuario;
        System.out.println("id para modificar: "+mod.id);
        mod.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
  /*  public void calcula () {        
    Calendar calendario1 = new GregorianCalendar();
    Date fechaHoraActual = new Date();


    calendario1.setTime(fechaHoraActual);
    ampm = calendario1.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";

    if(ampm.equals("PM")){
         int h = calendario1.get(Calendar.HOUR_OF_DAY);
         hora = h>9?""+h:"0"+h;
    }else{
         hora = calendario1.get(Calendar.HOUR_OF_DAY)>9?""+calendario1.get(Calendar.HOUR_OF_DAY):"0"+calendario1.get(Calendar.HOUR_OF_DAY);            
    }
    minutos = calendario1.get(Calendar.MINUTE)>9?""+calendario1.get(Calendar.MINUTE):"0"+calendario1.get(Calendar.MINUTE);
    segundos = calendario1.get(Calendar.SECOND)>9?""+calendario1.get(Calendar.SECOND):"0"+calendario1.get(Calendar.SECOND); 
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         // Construccion del arbol
             
    
        /* Create and display the form */
     /*   java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ppal().setVisible(true);

            }
        });
    }
    */
 
    public void queries(String query){
        try {
            try {
                con = new Conexion();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
            }

            //String apertura ="INSERT INTO  `sigi`.`caja` (`apertura`, `id_usuario`)VALUES ('"+openSalesValue+"', '"+Login.userId+"')";

            con.ejecutar(query);

        } catch (SQLException ex) {
            Logger.getLogger(moduloVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

/*public void setC(){
        try {
           // int q=0;
            rs=con.Consulta("SELECT * FROM usuarios WHERE nivel = '1' OR nivel = '0'");
            while(rs.next()){
                jCuser.addItem(rs.getString(5));
            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
        }

}*/
public void getT(String cad){
    aux3 = cad;
    System.out.println(aux3);
}

public void setT(String cad){
        String aux2 = cad;

}

public String objectToString(Object o) {
        String st;
        st = (String) o;
        return st;
    }
public int getFactura(){
        return rowCount;
}

public int getNumFac(){
        return numfac;
}

public void calcula () {        
    Calendar calendario1 = new GregorianCalendar();
    Date fechaHoraActual = new Date();


    calendario1.setTime(fechaHoraActual);
    ampm = calendario1.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";

    if(ampm.equals("PM")){
         int h = calendario1.get(Calendar.HOUR_OF_DAY);
         hora = h>9?""+h:"0"+h;
    }else{
         hora = calendario1.get(Calendar.HOUR_OF_DAY)>9?""+calendario1.get(Calendar.HOUR_OF_DAY):"0"+calendario1.get(Calendar.HOUR_OF_DAY);            
    }
    minutos = calendario1.get(Calendar.MINUTE)>9?""+calendario1.get(Calendar.MINUTE):"0"+calendario1.get(Calendar.MINUTE);
    segundos = calendario1.get(Calendar.SECOND)>9?""+calendario1.get(Calendar.SECOND):"0"+calendario1.get(Calendar.SECOND); 
}


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ppal().setVisible(true);
                
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ctacte;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public static javax.swing.JButton jBvta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLuserName;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lbHora1;
    // End of variables declaration//GEN-END:variables

public void setC(){
        try {
           // int q=0;
            rs=con.Consulta("SELECT * FROM usuarios WHERE nivel = '1' OR nivel = '0'");
            while(rs.next()){
//                jCuser.addItem(rs.getString(5));
            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
        }

}
   public void run() {
        Thread ct = Thread.currentThread();
         while(ct == h1) {   
          calcula();
         // lbHora.setText(hora + ":" + minutos + ":" + segundos + " "+ampm);
          lbHora1.setText(hora + ":" + minutos + ":" + segundos + " "+ampm);
         // lbHora2.setText(hora + ":" + minutos + ":" + segundos + " "+ampm);
          try {
              
           Thread.sleep(1000);
          }catch(InterruptedException e) {}
         }
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
